# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wie7pTOSKp4oQnj3bc-D6wasR2uu4Dxx
"""

from google.colab import files
from IPython.display import Image

uploaded= files.upload()

Image('kwiatki.png',
width=1000)